name: Deploy 

# https://github.com/nyakaz73/heroku-django-deploy/blob/master/.github/workflows/main.yml
# https://github.com/marketplace/actions/deploy-to-heroku#deploy-subdirectory
# https://github.com/nyakaz73/heroku-django-deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  # DISABLE AS DB IS BEING MIGRATED OUT OF HEROKu
#   Backend_Deploy:
#       runs-on: ubuntu-latest
#       defaults:
#         run:
#           working-directory: ./backend
#       if: "!contains(github.event.head_commit.message, '[ci skip]')"
#       name: Git Deploy job- A job to deploy django app to heroku using git
#       steps:
#         - name: Checkout
#           uses: actions/checkout@v2
#         - name: Deploy django to heroku
#           uses: nyakaz73/heroku-django-deploy@v0.68
#           with: 
#             heroku_app_name : ${{ secrets.HEROKU_APP_NAME }}
#             heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#             heroku_email_address: "israelias.js@gmail.com"
#             working-directory: ./backend
#             use_git: true
#             force_push: true

#           #Use the output from the hello step
#         - name: Get the output status
#           run: echo "${{ steps.deploy.outputs.status }}"
#         - name: Getting the files in directory
#           run: pwd

  Expo_Web_Build:
      # name: Export a an Expo web build for Vercel deployment
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./frontend
      # DISABLED DURING MIGRATION
      # needs: Backend_Deploy
      steps:
        - name: 🏗 Setup repo
          uses: actions/checkout@v2
        - name: 🏗 Setup Node
          uses: actions/setup-node@v2
          with:
            node-version: 16.x
            cache: yarn
            cache-dependency-path: './frontend/yarn.lock'
            
        - name: 🏗 Setup Expo
          uses: expo/expo-github-action@v5
          with:
            expo-version: 4.x
            expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
            expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
            expo-token: ${{ secrets.EXPO_TOKEN }}
            expo-cache: true
            
        - name: 📦 Install dependencies
          run: yarn install
        
        # DISABLE UNTIL MODULES ARE RESOLVED
        # - name: 🚀 Publish preview
          # run: expo publish --release-channel=pr-${{ github.event.number }} --non-interactive
        
        - name: 💬 Comment preview
          uses: expo/expo-github-action/preview-comment@v7
          with:
            channel: pr-${{ github.event.number }}

        
        # DISABLE INCONSEQUENTIAL
        # The web deployment is handled by Vercel
        
        # - run: expo build:web
          # - run: rm -fr .gitignore
          # - run: deploy

        #- run: cd web-build

        #- uses: amondnet/vercel-action@v20
          #with:
              #vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
         
              #vercel-org-id: ${{ secrets.ORG_ID}}  
              #vercel-project-id: ${{ secrets.PROJECT_ID}} 
              # working-directory: web-build


  # Frontend_Deploy:
  #     name: Deploy to Frontend To Vercel
  #     runs-on: ubuntu-latest
  #     defaults:
  #       run:
  #         working-directory: ./frontend
  #     needs: Expo_Web_Build
  #     steps:
  #       - run: yarn install
  #       - run: expo build:web
  #       - uses: actions/checkout@v2
  #       - uses: amondnet/vercel-action@v20
  #         with:
  #           vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
  #           # github-token: ${{ secrets.GITHUB_TOKEN }} #Optional 

  #           # vercel-args: '--prod' #Optional
  #           vercel-org-id: ${{ secrets.ORG_ID}}  #Required
  #           vercel-project-id: ${{ secrets.PROJECT_ID}} #Required 
  #           vercel-project-name: thrifthub
  #           working-directory: frontend/web-build
         
    
